name: Update IP List

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时执行一次
  workflow_dispatch:      # 支持手动触发
  push:                   # 手动 push 也可触发

jobs:
  update-ip-list:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run script
        run: |
          python collect_ips.py
          echo "--- ip.txt 内容预览 ---"
          head -n 10 ip.txt

      - name: Commit and push changes
        run: |
          git config --global user.email "tianshideyou@proton.me"
          git config --global user.name "tianshipapa"
          if [ -n "$(git status --porcelain)" ]; then
            git add ip.txt
            git commit -m "Automatic update"
            git pull --rebase origin main
            git push
          else
            echo "No changes detected, skipping commit."
          fi
